management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, metrics, prometheus
        exclude: threaddump, heapdump
  prometheus:
    metrics:
      export:
        enabled: true
