version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: chat_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - local

  application:
    container_name: chat-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/chat_service
      DATABASE_USERNAME: "root"
      DATABASE_PASSWORD: "root"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mysql
      - redis
    networks:
      - local

volumes:
  mysql_data:
  redis_data:

networks:
  local:
    driver: bridge
